# @Time    : 22/11/03 17:21
# @Author  : fyq
# @File    : network_error_map.py
# @Software: PyCharm

__author__ = 'fyq'


class NetworkErrorMap:

    def __init__(self):
        self.error_map = {
            1: "远程服务拒绝连接",
            2: "远程服务器在收到并处理整个答复之前过早关闭了连接",
            3: "远程服务器未发现",
            4: "连接超时",
            5: "操作在完成之前通过调用abort()或close()被取消",
            6: "SSL/TLS握手失败,无法建立加密通道,sslErrors()信号应该已经发出",
            7: "由于与网络断开连接,连接被中断,但是系统已经开始漫游到另一个接入点,应重新提交该请求,并在重新建立连接后立即处理",
            8: "由于与网络断开连接或无法启动网络,连接已断开",
            9: "由于平台策略,当前不允许后台请求",
            101: "与代理服务器的连接被拒绝(代理服务器不接受请求)",
            102: "代理服务器在收到并处理整个答复之前过早关闭了连接",
            103: "找不到代理主机名(代理主机名无效)",
            104: "与代理的连接超时或代理未及时答复发送的请求",
            105: "代理要求身份验证以满足请求,但不接受提供的任何凭据(如果有)",
            201: "对远程内容的访问被拒绝(类似于HTTP错误401)",
            202: "不允许对远程内容请求的操作",
            203: "在服务器上找不到远程内容(类似于HTTP错误404)",
            204: "远程服务器需要身份验证来服务内容,但未接受提供的凭据(如果有)",
            205: "请求需要再次发送,但这失败了,例如因为无法再次读取上传数据",
            206: "由于与资源的当前状态冲突,请求无法完成",
            207: "请求的资源在服务器上不再可用",
            401: "服务器遇到意外情况,无法满足请求",
            402: "服务器不支持满足请求所需的功能",
            403: "服务器此时无法处理该请求",
            301: "网络访问API无法接受该请求,因为协议未知",
            302: "请求的操作对此协议无效",
            99: "检测到未知的网络相关错误",
            199: "检测到未知的代理相关错误",
            299: "检测到与远程内容相关的未知错误",
            399: "检测到协议故障(解析错误、无效或意外响应等)",
            499: "检测到与服务器响应相关的未知错误",
        }

    def error_message(self, error):
        return self.error_map[error] if error in self.error_map else "未知错误({})".format(error)

